language: ruby
rvm:
  - 2.0.0

bundler_args: --without development

before_script:
  - psql -c 'create database restful_test;' -U postgres

script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
